### linux & osx dynamic linking, linux & os partially static linking
# newer cmake, gcc
language: cpp
sudo: required
dist: trusty
compile:
  - gcc
os:
  -linux
before_install:
#  - if [ $TRAVIS_OS_NAME = linux ]; then sudo sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && apt-get update -q; else brew install bar; fi
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
install:
  - sudo aptitude -f install g++-6 -y
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
  - mkdir build && cd build
  - cmake -DRSOCK_RELEASE=1 -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
  - make -j`grep -c '^processor' /proc/cpuinfo`

branches:
  only:
    - travis_dev
#-osx

