### linux & osx dynamic linking, linux & os partially static linking
# newer cmake, gcc
language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: linux
      compiler: clang

    - os: osx
      compiler: gcc

before_install:
  - if which apt-get ; then sudo sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -q; fi
install:
  - if which apt-get; then sudo aptitude -f install g++-6 -y; fi
before_script:
  - sudo chmod a+x xbuild/sh/travis_install.sh
script:
  - ./xbuild/sh/travis_install.sh